name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn run lint
      # - name: Test
      #   run: yarn run test:ci
      # - name: Publish Unit Test Results
      #   uses: EnricoMi/publish-unit-test-result-action/composite@v1
      #   if: always()
      #   with:
      #     files: junit.xml
      - name: Build
        run: PUBLIC_URL=/wizard yarn run build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy 🚀
        if: github.event_name == 'release'
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: build
